In [1]:
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

### Value Iteration
For a simple grid-world. Assuming an undiscounted, episodic MDP

Policy is equiprobable over all actions $a \in A$
$$
    A = \set{up, down, left, right}, \ \ 
    \pi(a|s) = \frac{1}{4}
$$
Reward $r_t=-1$ for all transitions

In [2]:
theta = 0.001 # accuracy of estimation
num_iters = 50
terminal_states = ((0,0), (3,3))
grid_size = 4
r_t = -1

In [3]:
def calculate_state_value(s: tuple, V_pi: np.ndarray, r_t: float, gamma: float):
    transitions = ( # all states s' after some action a
        (s[0] - 1, s[1]), # up
        (s[0] + 1, s[1]), # down
        (s[0], s[1] - 1), # left
        (s[0], s[1] + 1) # right
    ) 
    v_s = 0 # v_pi(s)
    for s_prime in transitions:
        if s_prime[0] < 0 or s_prime[0] >= grid_size or s_prime[1] < 0 or s_prime[1] >= grid_size:
            s_prime = s
        v = r_t + (gamma * V_pi[s_prime])
        v = v / 4 # each action has a 1/4 probability of being selected
        v_s += v
    return v_s

In [4]:
# initialize state-value estimates
V_pi = np.zeros((grid_size, grid_size))
i = 0
while True:
    if i in (0, 1, 2, 3, 10):
        print("Estimated V_pi at iter:", i)
        print(np.round(V_pi, decimals=2))
    i += 1
    delta = 0
    for row in range(grid_size):
        for col in range(grid_size):
            if (row, col) in terminal_states:
                continue
            v = V_pi[row, col]
            V_pi[row, col] = calculate_state_value((row, col), V_pi, r_t, gamma=1)
            delta = max(delta, abs(v - V_pi[row, col]))
    if delta < theta:
        break
print(f"Estimated value after completion ({i} iters)")
print(np.round(V_pi, decimals=2))

Estimated V_pi at iter: 0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Estimated V_pi at iter: 1
[[ 0.   -1.   -1.25 -1.31]
 [-1.   -1.5  -1.69 -1.75]
 [-1.25 -1.69 -1.84 -1.9 ]
 [-1.31 -1.75 -1.9   0.  ]]
Estimated V_pi at iter: 2
[[ 0.   -1.94 -2.55 -2.73]
 [-1.94 -2.81 -3.24 -3.4 ]
 [-2.55 -3.24 -3.57 -3.22]
 [-2.73 -3.4  -3.22  0.  ]]
Estimated V_pi at iter: 3
[[ 0.   -2.82 -3.83 -4.18]
 [-2.82 -4.03 -4.71 -4.88]
 [-3.83 -4.71 -4.96 -4.26]
 [-4.18 -4.88 -4.26  0.  ]]
Estimated V_pi at iter: 10
[[  0.    -7.83 -11.12 -12.23]
 [ -7.83 -10.42 -11.77 -11.86]
 [-11.12 -11.77 -11.05  -8.81]
 [-12.23 -11.86  -8.81   0.  ]]
Estimated value after completion (88 iters)
[[  0.   -13.99 -19.99 -21.99]
 [-13.99 -17.99 -19.99 -19.99]
 [-19.99 -19.99 -17.99 -13.99]
 [-21.99 -19.99 -13.99   0.  ]]
